In [1]:
import numpy as np

### The Basic (Это база)

In [2]:
a = np.array([1, 2, 3], dtype='int16')#второй праметр может быть dtype='int16' (для примера; тогда тип элемента будет int16)
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.6, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9.  8.6 7. ]
 [6.  5.  4. ]]


In [4]:
#узнать размерность
print(a.ndim, b.ndim)

1 2


In [5]:
#Массив сколько на сколько?
b.shape

(2, 3)

In [6]:
#типо массива
a.dtype

dtype('int16')

In [7]:
#размер элемента (в байтах)
a.itemsize

2

In [8]:
#получить число элементов
a.size

3

In [9]:
#Получить суммарное число байт на массив
a.nbytes

6

### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8,9,10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#Обращение к элементу по индексам
a[1, 5] 

13

In [12]:
#Выбрать строку
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [13]:
#Выбрать столбец
a[:, 3]

array([ 4, 11])

In [14]:
#Выбрать в строке, начиная с какого-то с каким-то шагом
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
a[1, 5] = 20 #изменение элемента
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
a[:, 2] = [1, 2] #полностью столбец с номером 2 (в 0-индексации) заменили 
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### Initializing Different Types of Arrays

In [22]:
#заполнить нулями матрицу нужной размерности
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((5, 2), dtype='int32') #единицами

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [26]:
np.full((2, 2), 99, dtype='float32') #заплнение чем нужно

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [27]:
np.full_like(a, 4) #заполнение нужного массива нужными числами

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
#заполнение рандомом
np.random.rand(4, 2) #параметры-размерность матрицы
# np.random.andom_sample(a.shape) #если заполнить рандомом конкретный массив

array([[0.20781796, 0.46895335],
       [0.47398203, 0.66183107],
       [0.78118186, 0.73001111],
       [0.98142092, 0.24366247]])

In [37]:
#рандом в интах
np.random.randint(2, 5, size=(3, 3))# числа [первый парметр,второй параметр)

array([[2, 2, 4],
       [4, 4, 4],
       [3, 4, 4]])

In [38]:
np.identity(4) #единичная матрица нужного размера

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
#repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis=0) #повторение элемента нужное число раз
print(r1)

[1 1 1 2 2 2 3 3 3]


In [46]:
output = np.ones((5, 5))
print(output)

q = np.zeros((3, 3))
q[1, 1] = 9
print(q)

output[1:4, 1:4] = q
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!!!

In [51]:
a = np.array([1, 2, 3])
#b = a
#b[0] = 100 #изменился и а
#поэтому копирование делается так
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


##Mathematics

In [52]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [53]:
a + 2

array([3, 4, 5, 6])

In [54]:
a - 2

array([-1,  0,  1,  2])

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [58]:
a**2

array([ 1,  4,  9, 16])

In [59]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##Linear Algebra

In [66]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b) #умножение матриц

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [67]:
c = np.identity(3)
np.linalg.det(c) #вычисление определителя

1.0

In [ ]:
#можно еще много всего делать при помощи np (след, обращать матрицы и тд), смотреть в документации

### Statistics

In [68]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.min(stats)

1

In [73]:
 np.max(stats,axis=1) #наибольшее в своих строках

array([3, 6])

In [74]:
np.sum(stats)

21

### Reorganizing Arrays

In [81]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((2, 2, 2)) #перестраиваем как нужно матрицу
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [82]:
# Verticaly stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2]) #уложили по строкам


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
# Horizontal stacking
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2)) #сцепляем две матрицы


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [ ]:
# если хотим считать txt, например, файл
# filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata = filedata.astype('int32)

### Advanced indexing and Boolean Masking

In [90]:
filedata = np.array([[1, 2, 3, 4, 5, 6], [10, 20, 30, 40, 50, 60]])
print(filedata)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]]


In [87]:
filedata[filedata > 15]

array([20, 30, 40, 50, 60])

In [88]:
# Ypu can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [89]:
np.any(filedata > 40, axis=0)

array([False, False, False, False,  True,  True])

In [93]:
(~(filedata > 15) & (filedata < 40))

array([[ True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False]])